### ISSUE TITLE
Path handling

### ISSUE THREAD

**Issue by kdungs** [apuignav/impactkit-proceedings#4]
Just created a small test contribution. Naively, I added an image to my contribution's folder and included it via `![…](image.png)`. When running the script this error occurs:

```
pandoc: Could not find image `image.png', skipping...
! Package pdftex.def Error: File `image.png' not found.

See the pdftex.def package documentation for explanation.
Type  H <return>  for immediate help.
 ...

l.70 \includegraphics{eplus_ProbNN.png}

pandoc: Error producing PDF from TeX source
Traceback (most recent call last):
  File "makeproc.py", line 112, in <module>
    make_proceedings()
  File "makeproc.py", line 103, in make_proceedings
    pdfs.append(build_single_pdf(dir_name))
  File "makeproc.py", line 52, in build_single_pdf
    raise OSError("Pandoc error")
OSError: Pandoc error
```

This should be easily fixed by adding the path to the folder in the `.md` file but it's a bit counter-intuitive. Maybe we can adjust the script to use the contribution's folder as base directory when building them.

**Comment by kdungs** [comment]
I am so stupid. This was already handled correctly.
